### ISSUE TITLE
elastic search 6.5.4 using log4j 2.11.1

### ISSUE THREAD

**Issue by er-pooja** [xeraa/elastic-docker#4]
We are using these
MediaWiki 1.35.3
PHP 7.4.23 (apache2handler)
MySQL 8.0.26
Lua 5.1.5
Elasticsearch 6.5.4 , Java 1.8.0 
As we cannot upgrade elastic search to upper version , Mediawiki 1.35.3 supports only elastic search 6.5.4 version.

in Elasticsearch 6.5.4  version of elastic search we have found that we have Log4j 2.11.1

So according to one artical we have added  Dlog4j2.formatMsgNoLookups=true
/etc/elasticserach/jvm.options 

and restarted the elastic server, pls let me know if anything else i need to do for Log4j2 security issue.
I have not removed the JndiLookup class yet.

Please suggest.

**Comment by xeraa** [comment]
Yes. Though an upgrade to the latest 6.x version would be strongly recommended as soon as that is possible.

https://xeraa.net/blog/2021_mitigate-log4j2-log4shell-elasticsearch/ for the longer version of this :)
